





export const categories = [
    {
      name: "Any Category",
      icon: "❔",
      id: -1,
      title: "Random Rush",
      caption: "Surprise yourself with trivia from every corner!",
    },
    {
      name: "General Knowledge",
      icon: "🧠",
      id: 9,
      title: "Brain Blast",
      caption: "Test the limits of your everyday knowledge!",
    },
    {
      name: "Books",
      icon: "📚",
      id: 10,
      title: "Page Turner",
      caption: "Flip through epic questions about beloved books!",
    },
    {
      name: "Film",
      icon: "🎞️",
      id: 11,
      title: "Screen Legends",
      caption: "Lights, camera, quiz action on cinema classics!",
    },
    {
      name: "Music",
      icon: "🎵",
      id: 12,
      title: "Beat Master",
      caption: "Drop the beat and rock this music quiz!",
    },
    {
      name: "Musical Theaters",
      icon: "🎭",
      id: 13,
      title: "Broadway Buzz",
      caption: "Spotlight's on! Show off your theater knowledge!",
    },
    {
      name: "Television",
      icon: "📺",
      id: 14,
      title: "Channel Champ",
      caption: "Binge-worthy questions about TV's finest moments!",
    },
    {
      name: "Video Games",
      icon: "🎮",
      id: 15,
      title: "Pixel Pro",
      caption: "Power up your gaming trivia to unlock victory!",
    },
    {
      name: "Board Games",
      icon: "🎲",
      id: 16,
      title: "Tabletop Titan",
      caption: "Roll for initiative on board game wisdom!",
    },
    {
      name: "Science & Nature",
      icon: "🌿",
      id: 17,
      title: "Wonder Lab",
      caption: "Explore the mysteries of our natural world!",
    },
    {
      name: "Computers",
      icon: "💻",
      id: 18,
      title: "Code Cracker",
      caption: "Debug your tech knowledge in this digital quiz!",
    },
    {
      name: "Mathematics",
      icon: "➗",
      id: 19,
      title: "Number Ninja",
      caption: "Calculate your way through these tricky questions!",
    },
    {
      name: "Mythology",
      icon: "⚡",
      id: 20,
      title: "Legend Lore",
      caption: "Challenge the gods with your mythical knowledge!",
    },
    {
      name: "Sports",
      icon: "🏅",
      id: 21,
      title: "Victory Lap",
      caption: "Sweat your way through sports trivia glory!",
    },
    {
      name: "Geography",
      icon: "🌍",
      id: 22,
      title: "Globe Trotter",
      caption: "Navigate the world's secrets like a pro!",
    },
    {
      name: "History",
      icon: "📜",
      id: 23,
      title: "Time Traveler",
      caption: "Journey through the ages of human history!",
    },
    {
      name: "Politics",
      icon: "🏛️",
      id: 24,
      title: "Power Player",
      caption: "Master the game of political knowledge!",
    },
    {
      name: "Art",
      icon: "🎨",
      id: 25,
      title: "Canvas Genius",
      caption: "Sketch your way through artistic excellence!",
    },
    {
      name: "Celebrities",
      icon: "🌟",
      id: 26,
      title: "Fame Game",
      caption: "Spotlight on stars, can you name them all?",
    },
    {
      name: "Animals",
      icon: "🐾",
      id: 27,
      title: "Wild Wisdom",
      caption: "Roar through questions about the animal kingdom!",
    },
    {
      name: "Vehicles",
      icon: "🚗",
      id: 28,
      title: "Speed Demon",
      caption: "Rev your engines for ultimate vehicle trivia!",
    },
    {
      name: "Comics",
      icon: "📖",
      id: 29,
      title: "Hero Quest",
      caption: "Unleash your inner superhero knowledge now!",
    },
    {
      name: "Gadgets",
      icon: "📱",
      id: 30,
      title: "Tech Wizard",
      caption: "Tap into your gadget knowledge superpowers!",
    },
    {
      name: "Japanese Anime & Manga",
      icon: "🉐",
      id: 31,
      title: "Otaku Challenge",
      caption: "Test your anime wisdom with this kawaii quiz!",
    },
    {
      name: "Cartoon & Animations",
      icon: "🐭",
      id: 32,
      title: "Toon Master",
      caption: "Animate your brain with cartoon trivia fun!",
    },
  ];
  